services:
  # MySQL Database
  db:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_manager
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Node.js Backend
  backend:
    image: yassird/expense-manager-backend:latest
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: expense_manager
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  # React Frontend
  frontend:
    image: yassird/expense-manager-frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay   # Use overlay networks in Docker Swarm

volumes:
  db_data:
